### ISSUE TITLE
关于我 - HeRaNO

### ISSUE THREAD

**Issue by HeRaNO** [HeRaNO/HeRaNO.github.io#2]
https://herano.github.io/about/ 

 你好，我是杨贺然，来自电子科技大学信息与软件工程学院。Hello, I’m Heran Yang (HeRaNO), who is from UESTC-SISE. 高中就读于哈尔滨师范大学附属中学，曾获 2016, 2017 年全国信息学奥林匹克竞赛联赛省级二等奖。I’ve graduated from MSAHRBNU, and was awarded the second prize of

**Comment by InterestingHui** [comment]
先抢个沙发，dgtql~
