### ISSUE TITLE
现在这个人在干啥 - HeRaNO

### ISSUE THREAD

**Issue by HeRaNO** [HeRaNO/HeRaNO.github.io#41]
https://herano.xyz/2020/08/23/%E7%8E%B0%E5%9C%A8%E8%BF%99%E4%B8%AA%E4%BA%BA%E5%9C%A8%E5%B9%B2%E5%95%A5/ 

 这个人没挂，友链啥的不用删（

**Comment by newhans** [comment]
大哥投实习嘛

**Comment by wlm3201** [comment]
我居然看完了。从友链的友链过来。
博主加油，怎么说这还是很多人可望而不可及的
